### ISSUE TITLE
set_cursor_position() and feed() 

### ISSUE THREAD

**Issue by occivink** [thestinger/vte-ng#1]
In the following case

```
long row, col;
vte_terminal_get_cursor_position(vte, &col, &row);
vte_terminal_set_cursor_position(vte, 0, 0);
vte_terminal_feed(vte, some_str, str, -1);
vte_terminal_set_cursor_position(vte, col, row);
```

`some_str` gets fed to the terminal at position [col,row] instead of [0,0] as I would like it. It seems like the second set_cursor_position() happens before feed().

**Comment by thestinger** [comment]
Termite and vte-ng are obsolete. Please use Alacritty instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
