### ISSUE TITLE
Add support for undercurl

### ISSUE THREAD

**Issue by kovidgoyal** [thestinger/vte-ng#11]
vim has support for generating undercurl escape codes on terminals via the t_Cs and t_Ce settings.
It would be nice to have vte-ng generate undercurls when it encounters these codes. Ideally, whatever escape code is chosen will also support setting the color of the undercurl independently of the foreground color. So for example, if the code chosen was 37, the sequence

```
<Esc>[37;1;r;g;bm
```

would start an undercurl in the color (r,g,b)

and the sequence

```
<Esc>[37;2m
```

would end the undecurl.

An undercurl is a curly underline, see for example the default spelling error highlighting in gvim. I dont know how diffcult actually rendering curly lines under text is in vte, but I hope not too bad. It should basically work the same as the existing underline code, with modifications to make it wiggle :)

**Comment by jelly** [comment]
We generally don't do vte development since gnome dev should take that up and hopefully this fork won't be needed in the future. The bug has been reported upstream here https://bugzilla.gnome.org/show_bug.cgi?id=721761

**Comment by kovidgoyal** [comment]
Apologies, I was under the impression that upstream had refused to merge the patches in this fork. Which was why I hoped you would be willing to add it. Maybe add a note to the README to prevent other people wasting your time in the future.

**Comment by kovidgoyal** [comment]
Just for the record -- I ended up writing my own terminal emulator that implements support for this (and lots of other features) https://github.com/kovidgoyal/kitty (the escape codes I chose were SGR 6, 58 and 59 to set the underline style and color. These seemed to be not widely used -- but they can always be changed in the future if a consensus around what codes should be used develops.
