### ISSUE TITLE
Incorrect width calculation since glibc switched to unicode 9

### ISSUE THREAD

**Issue by X-dark** [thestinger/vte-ng#12]
As discussed on: 
- https://github.com/powerline/powerline/issues/1652 
- https://bugzilla.gnome.org/show_bug.cgi?id=772812
- https://bugzilla.gnome.org/show_bug.cgi?id=772890

glibc update 2.50.1 which switched to Unicode 9, breaks some character wide calculation as they have a different width. This is seen when running tmux with powerline on termite, the status line scrolls instead of updating (because of incorrect calculation).

There some proposals to correct this on referenced bugs but as stated in https://github.com/thestinger/vte-ng/blob/0.46.0-ng/doc/ambiguous.txt this may not be the right solution.

**Comment by thestinger** [comment]
vte-ng is only a set of extra features for vte, so fixing issues in vte itself is out-of-scope. Any changes that happen in vte are incorporated into vte-ng when it moves to the latest stable release. Is there any issue here that doesn't impact every other vte terminal too?

**Comment by X-dark** [comment]
OK. Did not understand how vte and vte-ng projects articulate. Seems I need to wait for
this to be fixed in vte.
