### ISSUE TITLE
request for updated readme instructions

### ISSUE THREAD

**Issue by guisapol** [thestinger/vte-ng#13]
I'm not sure how to install vte-ng, I'd like to install termite

I've tried
https://askubuntu.com/questions/739563/how-to-compile-and-install-this/739614
but I end up getting this error when I automake --add-missing
automake: error: cannot open < gtk-doc.make: No such file or directory
and after configure I get
./configure: line 6650: syntax error near unexpected token `2.2'
and sudo make install I get 
make: *** No rule to make target 'install'.  Stop.

**Comment by guisapol** [comment]
Perhaps the readme could be update for those who aren't familiar on how to install the program

**Comment by jelly** [comment]
See https://github.com/thestinger/vte-ng/issues/8

> Only problems caused by the extensions in vte-ng are going to be supported on this tracker. Any build issues like this would also happen with vanilla VTE.
