### ISSUE TITLE
xfce4-terminal: symbol lookup error

### ISSUE THREAD

**Issue by N4d4** [thestinger/vte-ng#14]
after install vte-ng, i can't launch xfce terminal.
`xfce4-terminal: symbol lookup error: xfce4-terminal: undefined symbol: vte_regex_new_for_search`
- OS: Debian GNU/Linux testing (stretch) x86_64 
- DE: XFCE

**Comment by jelly** [comment]
Which branch of vte3-ng did you use? And really someone should make a debian package...

**Comment by thestinger** [comment]
This would also happen if you installed the same version of vte. It's not a bug that vte-ng is tied to vte versions.

**Comment by N4d4** [comment]
I've installed it with this [script](https://github.com/epsi-rns/dotfiles/blob/master/config/termite/termite-install.sh).
How can i fix this??

**Comment by epsi-rns** [comment]
rm /usr/local/lib/libvte-2.91.la \
/usr/local/lib/libvte-2.91.so /usr/local/lib/libvte-2.91.so.0 \
/usr/lib/libvte-2.91.so.0.4400.1

**Comment by jelly** [comment]
@N4d4 it's best to ask the author of this script. Since we don't support it.
