### ISSUE TITLE
Autogen reports that g++ does not support c++11 features.

### ISSUE THREAD

**Issue by zamlz** [thestinger/vte-ng#15]
It claims that a compiler with c++11 features is required, however, I am fairly confident that gcc version 4.9.4 has C++11 and can be compiled to through the use of the right flags. 

I am on void linux.

**Comment by jelly** [comment]
So can you show the output ./configure or whatever is broken?

**Comment by zamlz** [comment]
Rip, it was on my end, the compiler wasn't actually configured correctly. I'm sorry.
