### ISSUE TITLE
vte-ng breaks Gnome-terminal on the 3.22.1 stack.

### ISSUE THREAD

**Issue by BurningSmile** [thestinger/vte-ng#20]
Upon upgrading my system I found a bug with this package. When running gnome-terminal Version 3.24.1 it fails to start the terminal. When running gnome-terminal from a termite terminal this is the error output.

Error: Message recipient disconnected from message bus without replying

To reproduce
Install the Gnome 3.22.1 stack
Verify that gnome-terminal starts normally.
install vte3-ng for another terminal that requires it. (In my case termite terminal.)
Close gnome-terminal and try to reopen it.

Expected result
Gnome-terminal starts normally

Actual result 
gnome-terminal fails to start.

Host operating system
Arch Linux x64

**Comment by thestinger** [comment]
That's not supported yet. It's not a bug, the version simply hasn't been upgraded yet.

**Comment by BurningSmile** [comment]
Alright, thanks!

**Comment by jelly** [comment]
Package is now updated in [community]
