### ISSUE TITLE
Cannot install the lib

### ISSUE THREAD

**Issue by guest73** [thestinger/vte-ng#21]
After running autocong and then ./configure I get the following error
./configure: line 2312: syntax error near unexpected token `1.9'
./configure: line 2312: `AM_INIT_AUTOMAKE(1.9 foreign no-dist-gzip dist-bzip2 -Wno-portability)'

I am on Debian 9(testing).

Why there are no docs on how to install this lib anyway? And how can I solve the problem I have?

**Comment by thestinger** [comment]
Building vte-ng is the same as building vte so it's not in the scope of this patch set. The issue tracker also isn't used for support.
