### ISSUE TITLE
Support for font ligatures

### ISSUE THREAD

**Issue by shibumi** [thestinger/vte-ng#22]
Hello,
It would be nice if vte-ng could support fonts like `Fira Code`: https://github.com/tonsky/FiraCode
This font uses ligatures. It seems that there is demand for it...

for example:
https://github.com/thestinger/termite/issues/480

**Comment by jelly** [comment]
This will be a sad message, but this is something upstream VTE should fix. vte-ng is just a few patches on top of vte3, which should be merged by upstream. (Except they don't seem to be that font of patches which are not for gnome-terminal.

**Comment by jelly** [comment]
See upstream:
```
Christian Persch 2017-05-10 21:51:25 UTC
If there is a bug, it's not the same as comment 0. Ligatures are not supported (that's bug 584160).
```
https://bugzilla.gnome.org/show_bug.cgi?id=781597
