### ISSUE TITLE
Update library to 0.52

### ISSUE THREAD

**Issue by zlatin** [thestinger/vte-ng#25]
It would be great to update the library to newer version as gnome-terminal 3.28 doesn't work with this version.

**Comment by unclechu** [comment]
@zlatin According to the comments in this issue: https://github.com/thestinger/vte-ng/issues/26
This library is no longer maintained and I couldn't get any more details. I think the answer is: "just forget about it or maintain your own fork".

**Comment by paddyoneill** [comment]
@zlatin As pointed out by @unclechu this doesn't seem to be maintained anymore. I have a patch set that applies cleanly to 0.52.1. You can find them here [vte patches](https://github.com/paddyoneill/void-packages/tree/2ea8e44bb14b7f992105e186e8c9d2a0603187e8/srcpkgs/vte3/patches).

Not sure if anyone has a fork that is updated to 0.52 yet, so manually patching was the best way I found to do it
