### ISSUE TITLE
Make more clear how to install this library

### ISSUE THREAD

**Issue by unclechu** [thestinger/vte-ng#26]
I'm blowing my mind again and again when I'm installing new release of OS and building **vte-ng** again from scratch (in context of building the termite).

Usually I just go to the [releases](https://github.com/thestinger/vte-ng/releases) that I do for every other package, building some release, installing it to some `--prefix`, trying to build `termite` with it and then it fails. After scratching my head for hours I remember I supposed to clone repo not from some release (git-tag) but using a branch with name of a version plus `-ng` prefix which means it is really that **ng**. I do this mistake again and again, when time to reinstall OS comes I just already forget about this.

@thestinger Could you please do something with it? I'm quite sure there's someone apart me having the same issue. I'm not sure how to clarify this, maybe you need these releases for own purposes, maybe it would be better to add another `ng` releases, maybe extending `README` or something.

**Comment by thestinger** [comment]
If people are building it from source, having them check out the relevant tags isn't too much to ask.

I'm not one of the people maintaining these projects anymore so you're bugging the wrong person.

**Comment by unclechu** [comment]
@thestinger And who is actually maintaining this package these days who I supposed to address this to? Is it a different repo or this one (in this case it isn't supposed to be closed but readdressed)?

**Comment by unclechu** [comment]
Apart from this anyway, checking out relevant tags would be okay if there would be some relevant tags and my point was that it would be better if they at least would exist. It isn't obvious at first sight I shouldn't use "relevant tags" at all but some branch, and I think as a user "I'm looking at **vte-ng** package, not just **vte**, so here's a release I supposed to build".

**Comment by thestinger** [comment]
I'm sorry but I don't understand what you're saying and I honestly don't have time to dedicate to this.

**Comment by thestinger** [comment]
The tags certainly exist and you can see who works on it. Please note that I don't have any commits here anymore. I'm not involved. You pinged me from the start so I am getting emails about this and I don't have time to spend on it.
