### ISSUE TITLE
Rename package name to vte-ng

### ISSUE THREAD

**Issue by saivert** [thestinger/vte-ng#3]
Why don't you rename the package to vte-ng so it can be installed alongside upstream vte now that you have already forked it. Seems silly to still be replacing the systemwide upstream vte with your own version. No other software makes use of it other than termite that I know of.
Or at least use a VTE_API_MINOR_VERSION=91-ng. I already modify configure.ac when building it.

**Comment by thestinger** [comment]
Why? It's ABI compatible with VTE as it only adds a few extensions. There aren't any removed or changed signatures.

**Comment by Bob131** [comment]
+1 for this. A vte-ng specific pkgconfig would be handy for other users of vte-ng, and I agree wrt replacing the upstream lib: Fedora doesn't currently have vte-ng packages, so for me to write a spec that obsoletes vte3 means, for example, I can no longer share coredumps for applications using vte and assume everyone has the relevant debuginfo packages on hand.

It's also a pretty important package in terms of privacy/security (thinking stuff like sudo, email etc), so having a distro-signed build of the upstream library available to applications that aren't interested in vte-ng's additions is preferable to replacing the whole lot with a binary from a less trustworthy source (I'm thinking compromised/buggy toolchains, tampering etc, not malfeasance on your part :)

**Comment by jelly** [comment]
Ideally upstream merges these patches and vte-ng will not be needed anymore.
