### ISSUE TITLE
can't compile, ./configure failed, after running autoconf without problem

### ISSUE THREAD

**Issue by evanescente-ondine** [thestinger/vte-ng#30]
I can't compile vte-ng from the sources,
I run autoconf, then "./configure && make && make install" but it failed, saying (part that goes wrong):

```
3894: $? = 0
configure:3883: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-linux-gnu
Configured with: ../src/configure --enable-languages=ada,c,c++ --enable-dual-exceptions --enable-_cxa_atexit --enable-threads=posix --with-bugurl=URL:mailto:report@adacore.com --disable-nls --without-libiconv-prefix --disable-libstdcxx-pch --disable-libada --enable-checking=release --disable-multilib --with-mpfr=/boron.a/gnatmail/sandbox/community/x86_64-linux/mpfr_stable-c/install --with-gmp=/boron.a/gnatmail/sandbox/community/x86_64-linux/gmp_stable-c/install --with-mpc=/boron.a/gnatmail/sandbox/community/x86_64-linux/mpc_stable-c/install --with-build-time-tools=/boron.a/gnatmail/sandbox/community/x86_64-linux/gcc_current-c/build/buildtools/bin --prefix=/boron.a/gnatmail/sandbox/community/x86_64-linux/gcc_current-c/pkg --build=x86_64-pc-linux-gnu
Thread model: posix
gcc version 7.3.1 20180525 (for GNAT Community 2018 20180524) (GCC) 
configure:3894: $? = 0
configure:3883: gcc -V >&5
gcc: error: unrecognized command line option '-V'
```
What is the problem ?
No vte-ng, no termite, and that would uncool.

**Comment by jelly** [comment]
Which vte-ng branch?

**Comment by jelly** [comment]
Believe the upstream instructiosn are run ```./autogen.sh```. Also please post the config.log

**Comment by nnsite** [comment]
So, in the end, with the last verion (0.49.1) I couldn't get rid of "introspection requested but M4 macros are not installed" (despite gobject-introspection is here),
So I used instead this version: 0.46.0.a.
And it didn't complain. I'll report for problems with this version of vte-ng.

**Comment by nnsite** [comment]
Now, it always says "~/.config/termite/config parsing failed: No file or folder of this kind
So, it wasn't really a solution... But it should provide you with information.
By the way, this is my architecture: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Comment by jelly** [comment]
Arch uses 0.50.2.a which is probably a better idea.

**Comment by thestinger** [comment]
Termite and vte-ng are obsolete. Please use Alacritty instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
