### ISSUE TITLE
vala test app fails to build with vala 0.44

### ISSUE THREAD

**Issue by worldofpeace** [thestinger/vte-ng#32]
This was an [upstream issue](https://gitlab.gnome.org/GNOME/vte/issues/76) that was fixed in 
* https://gitlab.gnome.org/GNOME/vte/commit/53690d5cee51bdb7c3f7680d3c22b316b1086f2c 

it should be backported here.

**Comment by thestinger** [comment]
Termite and vte-ng are obsolete. Please use Alacritty instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
