### ISSUE TITLE
Compilation error on OpenBSD

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [thestinger/vte-ng#33]
Hi, I'm trying to compile on OpenBSD. However, OpenBSD does not use GNU Libtool.  

`hel$ autoreconf --force --install`                                                                                    
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal-1.10 line 617.
src/Makefile.am:28: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:28:   The usual way to define 'LIBTOOL' is to add 'AC_PROG_LIBTOOL'
src/Makefile.am:28:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:28:   If 'AC_PROG_LIBTOOL' is in 'configure.ac', make sure
src/Makefile.am:28:   its definition is in aclocal's search path.
autoreconf-2.65: automake failed with exit status: 1`

Adding AC_PROG_LIBTOOL to configure.ac: 
`hel$ autoreconf --force --install`
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal-1.10 line 617.
configure.ac: 100: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf-2.65: /usr/local/bin/autoconf-2.65 failed with exit status: 1

**Comment by brightersun99** [comment]
This and termite have all the signs of being total trash anyways. 

If a unix program doesn't work on openbsd, it's generally a big sign that its developer and said program are total crap.

**Comment by thestinger** [comment]
Termite and vte-ng are obsolete. Please use Alacritty instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
