### ISSUE TITLE
Feature request: API for controlling cursor visibility

### ISSUE THREAD

**Issue by omgold** [thestinger/vte-ng#34]
I like a lot to have the selection exposed via API, allowing e.g. Termite to implement keyboard selection. 

Unfortunately the feature is problematic to use when a curses-application in the terminal disables cursor visibilty. (One can still select via keyboard, but has to navigate blind). It could be easily fixed if command/selection would explicitly enable cursor visibility.

So what would be needed is 2 functions to:
- get current cursor visibilty state
- set cursor visibilty state

**Comment by thestinger** [comment]
Termite and vte-ng are obsolete. Please use Alacritty instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
