### ISSUE TITLE
error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by teto** [thestinger/vte-ng#4]
hi,
While launching autogen:
```Entering directory`.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file`./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file`m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file`m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file`m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:56: installing './compile'
configure.ac:65: installing './config.guess'
configure.ac:65: installing './config.sub'
configure.ac:16: installing './install-sh'
configure.ac:16: installing './missing'
doc/openi18n/Makefile.am: installing './depcomp'
src/Makefile.am:182: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
./autogen.sh  14,18s user 0,33s system 46% cpu 30,938 total

```
I am on Ubuntu 15.10. How can I solve this please ?
```

**Comment by thestinger** [comment]
This isn't related to the vte-ng changes. I don't have time to provide generic support.

**Comment by SrAceves** [comment]
@teto, this worked for me:
clone https://github.com/GNOME/gobject-introspection and look for the m4/ directory, where the `instrospection.m4` file is. Copy that file to `vte-ng/m4` directory and tun the `autogen.sh` again.
