### ISSUE TITLE
Fully fork from vte.

### ISSUE THREAD

**Issue by cyphar** [thestinger/vte-ng#5]
If there's no chance that vte upstream will merge your patches, maybe we should fork this repo entirely from vte. That way, you could parallel install both libvte and libvte-ng (making it much easier to package termite on distributions which individually package libvte as well).

**Comment by thestinger** [comment]
Why? It's ABI compatible with VTE so terminals using VTE can use this. No need to have both. Also not going to do extra work when this works fine.

**Comment by cyphar** [comment]
Because this isn't up-to-date with upstream (which is currently about to release `0.44`). Which means that release of new GNOME versions requires their `libvte`, while `termite` requires `libvte-ng`.

**Comment by thestinger** [comment]
It is up-to-date. The latest stable release is 0.42.4.

http://ftp.gnome.org/pub/GNOME/sources/vte/

**Comment by cyphar** [comment]
So, when `0.44` is released, this fork will track those updates?

**Comment by thestinger** [comment]
It follows along with the stable releases. There is no reason to waste time following along with master or supporting the unstable releases.

**Comment by jelly** [comment]
@cyphar Check my branch if you want to use the unstable version, no promises however. [1] 

[1] https://github.com/jelly/vte-ng/commits/0.43.2-ng
