### ISSUE TITLE
Strange cursor artifacts

### ISSUE THREAD

**Issue by beanaroo** [thestinger/vte-ng#6]
I immediately noticed this after updating.
Not sure how to describe it, please see screencast below.

![vte3-ng](https://cloud.githubusercontent.com/assets/1748909/14095671/2a4d9d44-f5bf-11e5-88b5-88713d8b781b.gif)

This only occurs when using vte3-ng. Tested on multiple terminal emulators.

**Comment by thestinger** [comment]
This doesn't happen for you with a matching version of vanilla VTE? I can't really understand how this would happen.

cc @jelly

**Comment by beanaroo** [comment]
Ah, I jumped the gun. The vte3 version I have available is slightly older. I don't have a matching version, but compiling from master, produces the same effect. I will move it over there. Sorry for the noise.

**Comment by thestinger** [comment]
No problem. We might have moved to the new version too early. I'm sure they'll fix it soon.

**Comment by beanaroo** [comment]
A [link to the bug](https://bugzilla.gnome.org/show_bug.cgi?id=764299) report for reference.

**Update:** Issue has been resolved upstream
