### ISSUE TITLE
Compile Error at 0.44.1b

### ISSUE THREAD

**Issue by ghost** [thestinger/vte-ng#8]
Error:

```

app.vala:159.39-159.42: warning: Argument 1: Cannot pass null to non-null parameter type
        search_entry.set_tooltip_text(null);
                                      ^^^^
app.vala:172.37-172.40: warning: Argument 1: Cannot pass null to non-null parameter type
      search_entry.set_tooltip_text(null);
                                    ^^^^
app.vala:23.1-23.33: error: UI resource not found: `/org/gnome/vte/test/app/ui/search-popover.ui'. Please make sure to specify the proper GResources xml files with --gresources.
class SearchPopover : Gtk.Popover
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app.vala:199.1-199.36: error: UI resource not found: `/org/gnome/vte/test/app/ui/window.ui'. Please make sure to specify the proper GResources xml files with --gresources.
class Window : Gtk.ApplicationWindow
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 2 warning(s)
Makefile:2060: recipe for target 'vte_2_91_vala.stamp' failed
make[2]: *** [vte_2_91_vala.stamp] Error 1
make[2]: Leaving directory '/root/vte-ng/src'
Makefile:2491: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/root/vte-ng/src'
Makefile:562: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

```

How t osolve this Issue? I am on debian.

**Comment by jelly** [comment]
Which version of Debian? Are you sure you have installed all of vte's makedeps?

**Comment by ghost** [comment]
What are all the vte's makedeps?

**Comment by jelly** [comment]
Not a Debian desktop user but you might want to install the build-depends of the vte3 package:

```
sudo apt-get build-dep vte3
```

**Comment by ghost** [comment]
There is no vte3, just following:

```

libvte-2.90-9       libvte-2.90-doc     libvte-2.91-dev     libvte-common
libvte-2.90-common  libvte-2.91-0       libvte-2.91-doc     libvte-dev
libvte-2.90-dev     libvte-2.91-common  libvte9             libvte-doc

```

**Comment by jelly** [comment]
Surely Debian Jessie has a vte3 package? https://packages.debian.org/source/jessie/vte3

**Comment by jelly** [comment]
And even then it fails and you'll need

```
apt-get install valac gperf libxml2-utils libgnutls28-dev
```

**Comment by q12321q** [comment]
I have the same error on debian 8. My STR:

``` sh
sudo apt-get install valac gperf libxml2-utils libgnutls28-dev
sudo apt-get build-dep vte3
./autogen.sh
make
```

It seems that file aliases are not recognized in _./src/app.gresource.xml_ but I don't know why. Valac version?
If I remove the aliases I manage to compile:

``` diff
diff --git a/src/app.gresource.xml b/src/app.gresource.xml
index 9095d32..d5c1110 100644
--- a/src/app.gresource.xml
+++ b/src/app.gresource.xml
@@ -16,8 +16,8 @@
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 -->
 <gresources>
-  <gresource prefix="/org/gnome/vte/test/app">
-    <file alias="ui/window.ui" compressed="true" preprocess="xml-stripblanks">app.ui</file>
-    <file alias="ui/search-popover.ui" compressed="true" preprocess="xml-stripblanks">search-popover.ui</file>
+  <gresource prefix="/org/gnome/vte/test/app/ui">
+    <file compressed="true" preprocess="xml-stripblanks">app.ui</file>
+    <file compressed="true" preprocess="xml-stripblanks">search-popover.ui</file>
   </gresource>
 </gresources>
diff --git a/src/app.vala b/src/app.vala
index 8104964..371dff2 100644
--- a/src/app.vala
+++ b/src/app.vala
@@ -195,7 +195,7 @@ class SearchPopover : Gtk.Popover

 } /* class SearchPopover */

-[GtkTemplate (ui = "/org/gnome/vte/test/app/ui/window.ui")]
+[GtkTemplate (ui = "/org/gnome/vte/test/app/ui/app.ui")]
 class Window : Gtk.ApplicationWindow
 {
   [GtkChild] private Gtk.Scrollbar scrollbar;
```

**Comment by thestinger** [comment]
Only problems caused by the extensions in vte-ng are going to be supported on this tracker. Any build issues like this would also happen with vanilla VTE.

**Comment by pedrecal** [comment]
I'm having this same issue on my Debian 8. I've installed vte3, and my app.gresource.xml looks like this:

`
<gresources>
  <gresource prefix="/org/gnome/vte/test/app">
    <file alias="ui/window.ui" compressed="true" preprocess="xml-stripblanks">app.ui</file>
    <file alias="ui/search-popover.ui" compressed="true" preprocess="xml-stripblanks">search-popover.ui</file>
  </gresource>
</gresources>
`

The error:

> pedrecal@avell-b155:~/git-src/vte-ng$ make
make[1]: Entering directory '/home/pedrecal/git-src/vte-ng/glade'
make[1]: Leaving directory '/home/pedrecal/git-src/vte-ng/glade'
make  all-recursive
make[1]: Entering directory '/home/pedrecal/git-src/vte-ng'
Making all in src
make[2]: Entering directory '/home/pedrecal/git-src/vte-ng/src'
make  all-am
make[3]: Entering directory '/home/pedrecal/git-src/vte-ng/src'
 VAPIGEN vte-2.91.vapi
  VALAC    vte_2_91_vala.stamp
app.vala:159.39-159.42: warning: Argument 1: Cannot pass null to non-null parameter type
        search_entry.set_tooltip_text(null);
                                      ^^^^
app.vala:172.37-172.40: warning: Argument 1: Cannot pass null to non-null parameter type
      search_entry.set_tooltip_text(null);
                                    ^^^^
app.vala:23.1-23.33: error: UI resource not found: `/org/gnome/vte/test/app/ui/search-popover.ui'. Please make sure to specify the proper GResources xml files with --gresources.
class SearchPopover : Gtk.Popover
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app.vala:199.1-199.36: error: UI resource not found: `/org/gnome/vte/test/app/ui/window.ui'. Please make sure to specify the proper GResources xml files with --gresources.
class Window : Gtk.ApplicationWindow
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 2 warning(s)
Makefile:2060: recipe for target 'vte_2_91_vala.stamp' failed
make[3]: *** [vte_2_91_vala.stamp] Error 1
make[3]: Leaving directory '/home/pedrecal/git-src/vte-ng/src'
Makefile:1192: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/pedrecal/git-src/vte-ng/src'
Makefile:563: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pedrecal/git-src/vte-ng'
Makefile:469: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by thestinger** [comment]
You would hit the same error building vanilla VTE, so it's not a vte-ng issue.
